server:
  port: 9000

#Database configuration

spring:
  data:
    mongodb:
      host: auth_db
      port: 27017
      database: auth_db

#JWT configuration

jwt:
  secret: rx3Uq+IbfJGh1iwRex6PNmOmNl2w3B7dbSt2bMdHOAqUdSSMSmc5V1FPVKkaMYyU5GZ0qH8PUsgF5rhuWqqt2w==
  expiration: 86400000

