server:
  port: 10000

#Database configuration

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: 'auth_db'

jwt:
  secret: "rx3Uq+IbfJGh1iwRex6PNmOmNl2w3B7dbSt2bMdHOAqUdSSMSmc5V1FPVKkaMYyU5GZ0qH8PUsgF5rhuWqqt2w=="
  expiration: 86400000

