server:
  port: 9001

#Database configuration

spring:
  data:
    mongodb:
      host: ticket_db
      port: 27017
      database: ${MONGO_DB_NAME_TICKET}
      username: admin # admin
      password: secret # secret
      authentication-database: admin



management:
  server:
    port: 9050          # ← run actuators on a side-port, keeps metrics off the main path
  endpoints:
    web:
      exposure:
        include: health,info,prometheus   # expose only what Prometheus (and you) need
  endpoint:
    health:
      show-details: "when_authorized"      # "always" if you want full health JSON
  metrics:
    tags:                                  # add high-cardinality tags here if desired
      application: ticketing-service
  prometheus:
    metrics:
      export:
        enabled: true
# src/main/resources/application-docker.yaml
logging:
  level:
    org.springframework.security: DEBUG
    com.ticket_management_system.auth_service.auth_service.security.jwt: DEBUG


