server:
  port: 10000

#Database configuration

spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: 'ticket_db'
      username: admin
      password: secret
      authentication-database: admin

logging:
  level:
    org.springframework.security: DEBUG
    com.ticket_management_system.auth_service.auth_service.security.jwt: DEBUG
    org.springframework.aop: DEBUG
    org.aspectj: TRACE

