server:
  port: 9001

#Database configuration

spring:
  data:
    mongodb:
      host: ticket_db
      port: ${MONGO_PORT_TICKET}
      database: ${MONGO_DB_NAME_TICKET}
      username: admin # admin
      password: secret # secret
      authentication-database: admin

# src/main/resources/application-docker.yaml
logging:
  level:
    org.springframework.security: DEBUG
    com.ticket_management_system.auth_service.auth_service.security.jwt: DEBUG

